### ISSUE TITLE
Using verapdf via CLI.

### ISSUE THREAD

**Issue by felipehw** [flathub/org.verapdf.veraPDF#1]
Hi!
How can I use verapdf via CLI?

I tried these options without success:
```
$ flatpak run --command=veraPDF org.verapdf.veraPDF --help
bwrap: execvp veraPDF: No such file or directory
$ flatpak run --command=verapdf org.verapdf.veraPDF --help
bwrap: execvp verapdf: No such file or directory
$ flatpak run --command=org.verapdf.veraPDF org.verapdf.veraPDF --help
bwrap: execvp org.verapdf.veraPDF: No such file or directory
```

Thanks!

**Comment by nbenitez** [comment]
It was not possible before, but I just pushed an update to flathub to include the CLI version of the app.

Make sure you update the app from flathub. Then you can run the CLI version as in these examples:

`flatpak run --command=verapdf org.verapdf.veraPDF --help`
`flatpak run --command=verapdf org.verapdf.veraPDF -x ~/Documents/your_sandbox_accesible_file.pdf`

If the pdf file you want to pass in it's not in a sandbox accesible directory (in this case if it's not under your home directory, as the app's permission is `--filesystem=home`) then you can use the `--file-forwarding` flag, as follows: 

`flatpak run --file-forwarding  --command=verapdf org.verapdf.veraPDF -x @@ /usr/inaccesible_file.pdf @@`

**Comment by felipehw** [comment]
Thanks!

**Comment by felipehw** [comment]
Just a small hint:
I believe the binary should have the name `verapdf` and not `verapdf-cli` because `verapdf` is the binary name at the official documentation: <https://docs.verapdf.org/cli/terminal/>.
This will avoid people have to find this issue to use the CLI,

**Comment by nbenitez** [comment]
Ok, I just pushed an update to flathub to rename it to 'verapdf' and also updated to last version 2.0.72

Thanks,
