### ISSUE TITLE
Please, merge my PR, so new release gets available.

### ISSUE THREAD

**Issue by zWhdmB5T** [flathub/org.verapdf.veraPDF#12]
@carlwilson @nbenitez Please, merge my PR, so new release gets available.

**Comment by carlwilson** [comment]
Thanks very much, @zWhdmB5T. I could be better at maintaining this. In truth, the file updates should be automated mainly by GitHub actions. This is merged and I've raised an [automated update issue](https://github.com/veraPDF/veraPDF-library/issues/1432) on the veraPDF library issue tracker.
