### ISSUE TITLE
Used runtime version is end-of-life

### ISSUE THREAD

**Issue by ghost** [flathub/org.verapdf.veraPDF#6]
Hello!

For a few weeks now I have been receiving the following message:
```
$ flatpak update
Looking for updates…
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   org.verapdf.veraPDF
```

Please update to the latest runtime version! Thank you!

**Comment by carlwilson** [comment]
Thanks for reporting this @lawncalculate I've fixed this and I suspect it's fixed my build as well. The new 1.20.3 should be good to go, going to add 1.22 shortly.
