### ISSUE TITLE
Request: veraPDF 1.24 (2023-06-28)

### ISSUE THREAD

**Issue by zWhdmB5T** [flathub/org.verapdf.veraPDF#8]
# Request: new version: veraPDF 1.24 (2023-06-28)
@carlwilson 
* https://verapdf.org/news/
* https://verapdf.org/2023/06/28/verapdf-1-24-released/
* https://github.com/veraPDF/veraPDF-library/releases/tag/v1.24.1

**Comment by ghost** [comment]
And please update to the latest runtime version!
